// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using openAPI.Data;

#nullable disable

namespace openAPI.Migrations
{
    [DbContext(typeof(HKContext))]
    [Migration("20230702194016_DB1")]
    partial class DB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("openAPI.Models.Aifile", b =>
                {
                    b.Property<string>("AifileId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AIFileId");

                    b.Property<string>("AifilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AIFilePath");

                    b.Property<string>("AifileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AIFileType");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AifileId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_AIFiles_ApplicationId");

                    b.ToTable("AIFiles", (string)null);
                });

            modelBuilder.Entity("openAPI.Models.Application", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.HasIndex(new[] { "MemberId" }, "IX_Applications_MemberId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("openAPI.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChatId");

                    b.HasIndex(new[] { "UserId" }, "IX_Chats_UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("openAPI.Models.Embedding", b =>
                {
                    b.Property<string>("EmbeddingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AifileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AIFileId");

                    b.Property<string>("EmbeddingAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QA");

                    b.HasKey("EmbeddingId");

                    b.HasIndex(new[] { "AifileId" }, "IX_Embedding_AIFileId");

                    b.ToTable("Embedding", (string)null);
                });

            modelBuilder.Entity("openAPI.Models.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("openAPI.Models.Qahistory", b =>
                {
                    b.Property<string>("QahistoryId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("QAHistoryId");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QahistoryA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QAHistoryA");

                    b.Property<string>("QahistoryQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QAHistoryQ");

                    b.Property<string>("QahistoryVectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QAHistoryVectors");

                    b.HasKey("QahistoryId");

                    b.HasIndex(new[] { "ChatId" }, "IX_QAHistory_ChatId");

                    b.ToTable("QAHistory", (string)null);
                });

            modelBuilder.Entity("openAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_Users_ApplicationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("openAPI.Models.Aifile", b =>
                {
                    b.HasOne("openAPI.Models.Application", "Application")
                        .WithMany("Aifile")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("openAPI.Models.Application", b =>
                {
                    b.HasOne("openAPI.Models.Member", "Member")
                        .WithMany("Application")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("openAPI.Models.Chat", b =>
                {
                    b.HasOne("openAPI.Models.User", "User")
                        .WithMany("Chat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("openAPI.Models.Embedding", b =>
                {
                    b.HasOne("openAPI.Models.Aifile", "Aifile")
                        .WithMany("Embeddings")
                        .HasForeignKey("AifileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aifile");
                });

            modelBuilder.Entity("openAPI.Models.Qahistory", b =>
                {
                    b.HasOne("openAPI.Models.Chat", "Chat")
                        .WithMany("Qahistorie")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("openAPI.Models.User", b =>
                {
                    b.HasOne("openAPI.Models.Application", "Application")
                        .WithMany("User")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("openAPI.Models.Aifile", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("openAPI.Models.Application", b =>
                {
                    b.Navigation("Aifile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("openAPI.Models.Chat", b =>
                {
                    b.Navigation("Qahistorie");
                });

            modelBuilder.Entity("openAPI.Models.Member", b =>
                {
                    b.Navigation("Application");
                });

            modelBuilder.Entity("openAPI.Models.User", b =>
                {
                    b.Navigation("Chat");
                });
#pragma warning restore 612, 618
        }
    }
}
